"""Add address field to Project model

Revision ID: 12ddeb9e606f
Revises: 2fc09de59c6a
Create Date: 2025-02-21 16:46:42.406623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ddeb9e606f'
down_revision = '2fc09de59c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
