"""Add project details fields

Revision ID: 2fc09de59c6a
Revises: 
Create Date: 2025-02-21 16:02:45.529058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc09de59c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('attn', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contractor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contractor_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_contact_phone', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('job_contact_phone')
        batch_op.drop_column('job_contact')
        batch_op.drop_column('contractor_email')
        batch_op.drop_column('contractor_name')
        batch_op.drop_column('attn')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
